name: Deploy React App

on:
  push:
    branches:
      - main # запускаем при пуше в main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Подключаемся к серверу и запускаем deploy.sh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/test-deploy/.deploy
            ./deploy.sh
